{"trial_id": "0173", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "activation", "default": "relu", "conditions": [], "values": ["relu", "tanh", "sigmoid", "leaky_relu"], "ordered": false}}, {"class_name": "Int", "config": {"name": "first_units", "default": null, "conditions": [], "min_value": 2, "max_value": 24, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 16, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_2", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_3", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_4", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_5", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_6", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_7", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_8", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_9", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_10", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_11", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_12", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_13", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_14", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_15", "default": null, "conditions": [], "min_value": 2, "max_value": 32, "step": 2, "sampling": "linear"}}], "values": {"activation": "tanh", "first_units": 20, "num_layers": 6, "units_0": 6, "units_1": 4, "units_2": 12, "units_3": 22, "units_4": 14, "units_5": 22, "units_6": 20, "units_7": 24, "units_8": 22, "units_9": 28, "units_10": 10, "units_11": 20, "units_12": 28, "units_13": 10, "units_14": 16, "units_15": 16, "tuner/epochs": 50, "tuner/initial_epoch": 0, "tuner/bracket": 0, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tensorflow/python/eager/execute.py\", line 59, in quick_execute\n    except TypeError as e:\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node AssignVariableOp_1 defined at (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n\n  File \"<frozen runpy>\", line 88, in _run_code\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py\", line 17, in <module>\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 701, in start\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/opt/anaconda3/lib/python3.12/asyncio/base_events.py\", line 639, in run_forever\n\n  File \"/opt/anaconda3/lib/python3.12/asyncio/base_events.py\", line 1985, in _run_once\n\n  File \"/opt/anaconda3/lib/python3.12/asyncio/events.py\", line 88, in _run\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in dispatch_queue\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 523, in process_one\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 429, in dispatch_shell\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 767, in execute_request\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 429, in do_execute\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n\n  File \"/var/folders/2v/kgb9p_hn6ss9mqhg1hbvvgxh0000gn/T/ipykernel_1335/2348387933.py\", line 1, in <module>\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 371, in fit\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 219, in function\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 132, in multi_step_on_iterator\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 113, in one_step_on_data\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 67, in train_step\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/metrics/reduction_metrics.py\", line 149, in update_state\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/common/variables.py\", line 267, in assign_add\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/common/variables.py\", line 263, in assign\n\n  File \"/opt/anaconda3/lib/python3.12/site-packages/keras/src/backend/tensorflow/core.py\", line 65, in _direct_assign\n\nTrying to assign to variable with tensor with wrong shape. Expected [] got [0]\n\t [[{{node AssignVariableOp_1}}]] [Op:__inference_multi_step_on_iterator_30853081]\n"}